version: "3"
services:
  web:
    image: nginx
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    depends_on:
      - app

  # The Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www
    entrypoint: /usr/local/bin/initialize.sh php-fpm
    volumes:
      - ./:/var/www